# Generated by Django 4.1.3 on 2022-11-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_rival'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='pixel.jpg', upload_to='upload/products/'),
        ),
    ]
