# Generated by Django 4.1.3 on 2022-11-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rival',
        ),
    ]
