# Generated by Django 4.1.3 on 2022-12-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cutomer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cutomer',
            new_name='customer',
        ),
    ]
