# Generated by Django 4.1.3 on 2022-12-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_cutomer_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='mobile_number',
        ),
    ]
